CREATE TABLE `nsi`.`user` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `PasswordHash` VARCHAR(500) NOT NULL,
  `Username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE)
ENGINE = InnoDB
KEY_BLOCK_SIZE = 4;